import './js/pagination';
import './js/main';
import './js/movie-modal';
import './js/library';
import './js/search';
import './js/logo';
import './js/dark-mode';
import './js/footer'
import './js/scroll-button'
